#############################################################################
# Makefile for building: PointCloud.app/Contents/MacOS/PointCloud
# Generated by qmake (2.01a) (Qt 4.8.0) on: Fri Nov 4 01:44:57 2011
# Project:  PointCloud.pro
# Template: app
# Command: /Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 CONFIG+=declarative_debug -o Makefile PointCloud.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc-4.2
CXX           = g++-4.2
DEFINES       = -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 -I. -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtCore.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtGui.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtOpenGL -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtXml.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtXml -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include -I/Library/Frameworks/QGLViewer.framework/Versions/2/Headers -I../../kinect/OpenNI-Bin-MacOSX-v1.3.2.1/Include -I../../OpenCV-2.3.0/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LINK          = g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Users/oonomakoto/OpenCV-2.3.0/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_calib3d -lopencv_video -lopencv_features2d -lopencv_flann -L/Users/oonomakoto/cvblob/lib -lcvblob -L/Users/oonomakoto/kinect/OpenNI-Bin-MacOSX-v1.3.2.1/Lib -lOpenNI -lnimCodecs -L/Library/Frameworks -framework QGLViewer -framework QtXml -framework QtOpenGL -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		PointCloudView.cpp \
		NiUserTracker.cpp moc_MainWindow.cpp \
		moc_PointCloudView.cpp \
		moc_NiUserTracker.cpp
OBJECTS       = main.o \
		MainWindow.o \
		PointCloudView.o \
		NiUserTracker.o \
		moc_MainWindow.o \
		moc_PointCloudView.o \
		moc_NiUserTracker.o
DIST          = ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		PointCloud.pro
QMAKE_TARGET  = PointCloud
DESTDIR       = 
TARGET        = PointCloud.app/Contents/MacOS/PointCloud

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile PointCloud.app/Contents/PkgInfo PointCloud.app/Contents/Resources/empty.lproj PointCloud.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) PointCloud.app/Contents/MacOS/ || $(MKDIR) PointCloud.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PointCloud.pro  ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42/qmake.conf ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 CONFIG+=declarative_debug -o Makefile PointCloud.pro
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 CONFIG+=declarative_debug -o Makefile PointCloud.pro

PointCloud.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) PointCloud.app/Contents || $(MKDIR) PointCloud.app/Contents 
	@$(DEL_FILE) PointCloud.app/Contents/PkgInfo
	@echo "APPL????" >PointCloud.app/Contents/PkgInfo
PointCloud.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) PointCloud.app/Contents/Resources || $(MKDIR) PointCloud.app/Contents/Resources 
	@touch PointCloud.app/Contents/Resources/empty.lproj
	
PointCloud.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) PointCloud.app/Contents || $(MKDIR) PointCloud.app/Contents 
	@$(DEL_FILE) PointCloud.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PointCloud,g" -e "s,@TYPEINFO@,????,g" ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42/Info.plist.app >PointCloud.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/PointCloud1.0.0 || $(MKDIR) .tmp/PointCloud1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PointCloud1.0.0/ && $(COPY_FILE) --parents MainWindow.h PointCloudView.h NiUserTracker.h .tmp/PointCloud1.0.0/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp PointCloudView.cpp NiUserTracker.cpp .tmp/PointCloud1.0.0/ && (cd `dirname .tmp/PointCloud1.0.0` && $(TAR) PointCloud1.0.0.tar PointCloud1.0.0 && $(COMPRESS) PointCloud1.0.0.tar) && $(MOVE) `dirname .tmp/PointCloud1.0.0`/PointCloud1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PointCloud1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r PointCloud.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_MainWindow.cpp moc_PointCloudView.cpp moc_NiUserTracker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_PointCloudView.cpp moc_NiUserTracker.cpp
moc_MainWindow.cpp: PointCloudView.h \
		NiUserTracker.h \
		MainWindow.h
	/Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ MainWindow.h -o moc_MainWindow.cpp

moc_PointCloudView.cpp: NiUserTracker.h \
		PointCloudView.h
	/Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ PointCloudView.h -o moc_PointCloudView.cpp

moc_NiUserTracker.cpp: NiUserTracker.h
	/Users/oonomakoto/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ NiUserTracker.h -o moc_NiUserTracker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp MainWindow.h \
		PointCloudView.h \
		NiUserTracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		PointCloudView.h \
		NiUserTracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

PointCloudView.o: PointCloudView.cpp PointCloudView.h \
		NiUserTracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointCloudView.o PointCloudView.cpp

NiUserTracker.o: NiUserTracker.cpp NiUserTracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NiUserTracker.o NiUserTracker.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_PointCloudView.o: moc_PointCloudView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PointCloudView.o moc_PointCloudView.cpp

moc_NiUserTracker.o: moc_NiUserTracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NiUserTracker.o moc_NiUserTracker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

